apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
    version: v1
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: server
---
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: server-split
spec:
  service: server
  backends:
    - service: server-v1
      weight: 100