apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
---
apiVersion: v1
kind: Service
metadata:
  name: server-v2
  labels:
    app: server
    version: v2
    service: server
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: server
    version: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
      version: v2
  template:
    metadata:
      labels:
        app: server
        version: v2
    spec:
      serviceAccountName: server
      containers:
        - image: grpc-load-balancing/server:1
          name: server
          ports:
            - containerPort: 50051
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
