apiVersion: v1
kind: ServiceAccount
metadata:
  name: xds
---
apiVersion: v1
kind: Service
metadata:
  name: xds
  labels:
    app: xds
    service: xds
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 9002
      targetPort: 9002
  selector:
    app: xds
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xds
      version: v1
  template:
    metadata:
      labels:
        app: xds
        version: v1
    spec:
      volumes:
        - name: xdsconfig
          configMap:
            name: xdsconfig
      serviceAccountName: xds
      containers:
        - image: grpc-load-balancing/xds:1
          name: xds
          ports:
            - containerPort: 9002
          volumeMounts:
            - mountPath: /config
              name: xdsconfig
---
kind: ConfigMap
metadata:
  name: xdsconfig
apiVersion: v1
data:
  config.yaml: |
    name: xdsconfig
    spec:
      listeners:
        - name: listener_0
          address: 0.0.0.0
          port: 8080
          routes:
            - name: local_route
              prefix: /
              clusters:
                - server_cluster
      clusters:
        - name: server_cluster
          endpoints:
            - address: server-v1
              port: 50051

