apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
    version: v1
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: server
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: server
spec:
  parentRefs:
    - kind: Service
      name: server
  rules:
    - backendRefs:
      - name: server-v2
        port: 50051
        weight: 100
